# Pandas Practical Test (30 Marks)

Dataset: NetFlix.csv

Time: 1 Hour

Maximum Marks: 30

Name:

College-Id:

Q1. Load the dataset and display the first 10 records.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

Q2. Find:

a) Number of rows and columns

b) Data types of all columns

In [8]:
df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration         int64
genres          object
description     object
dtype: object

Q3. Display the names of all columns in the dataset.

In [6]:
df.columns.tolist()

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'genres',
 'description']

Q4. Find the number of missing values present in each column.

In [13]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

Q5. How many Movies and TV Shows are available in the dataset?

In [14]:
df["type"].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

Q6. Display all titles released after 2020.

In [37]:
df[df["release_year"] > 2020]["title"]

250                                       Carmen Sandiego
319                                              Charming
397     Chris Rock Total Blackout: The Tamborine Exten...
492                                             Cobra Kai
574               Crack: Cocaine, Corruption & Conspiracy
589                           Creating The Queen's Gambit
869                                        Disenchantment
962                                   Dream Home Makeover
1477                                    Gabby's Dollhouse
1860                        Headspace Guide to Meditation
1937                                                Hilda
1950                               History of Swear Words
2245                  Inside the World’s Toughest Prisons
3138                                                Lupin
3431                   Mighty Little Bheem: Kite Festival
3528                                              Monarca
3769                                    Nailed It! Mexico
3855          Night Stalker: The Hunt for a Serial Killer
4125                                     Outside the Wire
4407                                  Pretend It’s a City
4562    Ratones Paranoicos: The Band that Rocked Argen...
5401                                          Stuck Apart
5470                                      Surviving Death
6087                                 The Idhun Chronicles
6302                         The Minimalists: Less Is Now
6337                               The Netflix Afterparty
6914                        Tribhanga - Tedhi Medhi Crazy
7281                            What Happened to Mr. Cha?
7301                          What Would Sophia Loren Do?
7384                                             Wish You
7767                                         Bling Empire
Name: title, dtype: object

Q7. Find the 10 oldest titles in the dataset based on release_year.

In [38]:
df.sort_values(by="release_year", ascending=False).head(10)["title"]

492                                             Cobra Kai
250                                       Carmen Sandiego
397     Chris Rock Total Blackout: The Tamborine Exten...
1937                                                Hilda
3769                                    Nailed It! Mexico
589                           Creating The Queen's Gambit
574               Crack: Cocaine, Corruption & Conspiracy
3528                                              Monarca
6914                        Tribhanga - Tedhi Medhi Crazy
7281                            What Happened to Mr. Cha?
Name: title, dtype: object

Q8. Find all content having rating "PG-13" and display their titles.

In [39]:
df[df["rating"] == "PG-13"]["title"]

6                           Blue Streak
13                             3 Idiots
85                        Brain on Fire
121     Bring It On: Worldwide Showdown
155                               Bully
                     ...
7752                          Blackfish
7754                     3 Days to Kill
7755                           Blackway
7776                      3 Generations
7785                       Blue Jasmine
Name: title, Length: 386, dtype: object

Q9. Count the number of titles available in each rating category.

In [22]:
df["rating"].value_counts()

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

Q10. Find the average duration of all Movies and TV Shows separately.

In [25]:
df.groupby("type")["duration"].mean()

type
Movie      99.307978
TV Show     1.775934
Name: duration, dtype: float64

Q11. Find the director who has directed the maximum number of titles.

In [28]:
df["director"].value_counts().head(1)

director
Raúl Campos, Jan Suter    18
Name: count, dtype: int64

Q12. Find the release year that contains the maximum number of titles.

In [30]:
df["release_year"].value_counts().head(1)

release_year
2018    1121
Name: count, dtype: int64

Q13. Display all titles whose genre contains the word "Drama".

In [33]:
df[df["genres"].str.contains("Drama", case=False, na=False)][["title"]]

                          title
0                            3%
2                    3 Heroines
7                Blue Valentine
13                     3 Idiots
21                        Bobby
...                         ...
7779                  Bloodline
7781                       Blow
7784  Blue Is the Warmest Color
7785               Blue Jasmine
7786                   Blue Jay

[2810 rows x 1 columns]

Q14. Find the top 5 most common genres.

In [40]:
df["genres"].value_counts().head(5)

genres
Documentaries                                       334
Stand-Up Comedy                                     321
Dramas, International Movies                        320
Comedies, Dramas, International Movies              243
Dramas, Independent Movies, International Movies    215
Name: count, dtype: int64

Q15. Export all Movies released after 2018 to a new CSV file named recent_movies.csv.

In [42]:
recent_movies = df[(df["type"] == "Movie") & (df["release_year"] > 2018)]
recent_movies.to_csv("recent_movies.csv", index=False)
print("File Saved Successfully")

File Saved Successfully